### ISSUE TITLE
Remove fake data

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/faker#1]
Would be nice if fake data could easily be removed.

**Comment by andyinabox** [comment]
@haroldangenent  It looks to me like faker sets a meta key `_fake` when generating posts, so I was able to delete fake posts with:

```bash
wp post delete $(wp post list --meta_key='_fake' --meta_value='1' --format=ids)
```

**Comment by haroldangenent** [comment]
@andyinabox Thanks for your help! This meta key is indeed set to later build this feature (which is still in review at #14).
