### ISSUE TITLE
How is Faker installed?

### ISSUE THREAD

**Issue by vinkla** [trendwerk/faker#15]
How does this package install the `fzaninotto/faker` package? I want to use the latest version of the`fzaninotto/faker` package. Isn't it installed with Composer?

**Comment by vinkla** [comment]
Installed a later version of `fzaninotto/faker` locally and I get the latest updates.

**Comment by vinkla** [comment]
I'm reopening this. I'm curious how you install the `fzaninotto/faker` package. How do you do it?

**Comment by haroldangenent** [comment]
@vinkla This project requires [`nelmio/alice`](https://github.com/trendwerk/faker/blob/master/composer.json#L25), which in turn requires [`fzaninotto/faker`](https://github.com/nelmio/alice/blob/2.x/composer.json#L23). Hope that answers your question!

**Comment by vinkla** [comment]
Oh, I see. Thanks for clarifying that.
