### ISSUE TITLE
ACF Issue

### ISSUE THREAD

**Issue by vinkla** [trendwerk/faker#16]
The ACF no longer works for me in the latest version of ACF (5.6.0). Not sure how to debug this. Does it work for you in the latest beta of ACF?

**Comment by haroldangenent** [comment]
@vinkla I didn't get a chance to test on the latest ACF beta, but the latest stable version seems OK. There might be a breaking change in the latest beta, but that seems unlikely, since this package [only uses some basic ACF functions]( https://github.com/trendwerk/faker/blob/master/src/Entity/Post.php#L44-L49).

Do you get any errors when you turn on the WordPress debug log?

**Comment by vinkla** [comment]
> Do you get any errors when you turn on the WordPress debug log?

No, the debug log shows no errors what so ever. The fields are just empty.

**Comment by haroldangenent** [comment]
Just got a chance to test ACF 5.6. Tested RC-1 and beta 2, but they both still seem to work (using either field keys and field names). I'm not sure how to reproduce this. 

@vinkla Could you share your fixtures file or do you have any steps to reproduce this?

**Comment by vinkla** [comment]
Sorry for not writing a more thorough bug report. Is there anything else I can test or debug to help us fix this issue?

**Comment by haroldangenent** [comment]
I'm not sure if you did this already, but you could test this out on a clean WordPress install (latest), without any plugins and specific themes. If the problem persists, you could share steps to reproduce this (including your fixtures files).

Another option would be to debug the code to see where things go wrong exactly. [This](https://github.com/trendwerk/faker/blob/master/src/Entity/Post.php#L44-L49) would be a good place to start.

**Comment by haroldangenent** [comment]
@vinkla Did you ever manage to debug / fix your problem? Or do you have any steps for me to reproduce this issue?

**Comment by vinkla** [comment]
Sorry, haven't had the time yet to test. Still on summer vacation. Will try installing it on a fresh install in the next few weeks.

**Comment by haroldangenent** [comment]
Okay, have fun 🌴

**Comment by vinkla** [comment]
Sorry for not getting back on this. Haven't had the time to try it out again and probably wont in a near future. I'm closing this.
