### ISSUE TITLE
[Feature Request] Submit to Packagist

### ISSUE THREAD

**Issue by vinkla** [trendwerk/faker#18]
Since WP-CLI version 2.0 it is now possible to register commands simply by requiring a package which registers a command. Basically installing `wp-cli/wp-cli` and `trendwerk/faker` as development dependencies makes it possible to run `wp faker` in the current project:

```json
"require-dev": {
    "trendwerk/faker": "^0.1.1",
    "wp-cli/wp-cli": "^2.0"
}
```

Though, this package isn't submitted to Packagist (yet). Currently one has to add the repository URL to the `repositories` object in `composer.json` file.

Would it be possible if you registered it on Packagist?

**Comment by haroldangenent** [comment]
Thanks for the heads-up: https://packagist.org/packages/trendwerk/faker.

**Comment by vinkla** [comment]
Thank you @haroldangenent!
