### ISSUE TITLE
Consider adding functional tests to this project

### ISSUE THREAD

**Issue by danielbachhuber** [trendwerk/faker#3]
Functional tests are an integral ingredient of highly-quality, maintainable commands. WP-CLI tries to make it as easy as possible to add functional tests to your package with its `wp scaffold package-tests` command:

https://github.com/wp-cli/scaffold-package-command#wp-scaffold-package-tests

I'd encourage you to consider adding functional tests to your package :) By starting your functional tests early on, it also makes it much easier to maintain your project over time.

**Comment by haroldangenent** [comment]
Yes, you're right. I didn't have too much time (and I am not too familiar with writing tests) so I decided to drop them at first. I will add them when I find some time to work on this.

Do you have any tips on good resources about writing (functional) tests?

**Comment by danielbachhuber** [comment]
> Do you have any tips on good resources about writing (functional) tests?

I'd suggest starting with:
- https://github.com/wp-cli/scaffold-package-command#wp-scaffold-package-tests
- https://wp-cli.org/docs/pull-requests/#running-and-writing-tests

**Comment by haroldangenent** [comment]
Thanks, I really appreciate your feedback and tips!

**Comment by haroldangenent** [comment]
Added some functional tests in #6.

@danielbachhuber It really would be great if you find some time to glance over these.

By the way, I ran in to https://github.com/wp-cli/scaffold-package-command/issues/19. Fixed this by including `vendor/autoload.php` instead of the autoloaded file required by `FeatureContext.php`. When requiring `vendor/autoload.php` both PSR-4, dependencies and autoloaded files are properly loaded (See [this line](https://github.com/trendwerk/faker/blob/tests/features/bootstrap/FeatureContext.php#L20)).

**Comment by danielbachhuber** [comment]
> It really would be great if you find some time to glance over these.

Looks like you're part of the way there! I'd also include tests to assert the before and after state of the database.

> Fixed this by including vendor/autoload.php instead of the autoloaded file required by `FeatureContext.php`

Did you regenerate the autoloader in the process too?

**Comment by haroldangenent** [comment]
Been away for a few weeks, got around to looking at the tests today.

> I'd also include tests to assert the before and after state of the database.

I already felt this tests were not doing any actual checks, but followed the example of some other packages. Thanks for pointing me in the right direction.

Included a test that checks for the newly generated posts in #6. What do you think?

> Did you regenerate the autoloader in the process too?

No, not specifically for this issue, but the autoloader already included my local repository for development purposes.

**Comment by danielbachhuber** [comment]
> Included a test that checks for the newly generated posts in #6. What do you think?

Looks good!
