### ISSUE TITLE
Generate fake attachments

### ISSUE THREAD

**Issue by codytooker** [trendwerk/faker#7]
Anyway to create a post thumbnail with a certain image here.  Either using the faker library or even just a special image in the theme or something?

**Comment by haroldangenent** [comment]
Currently, it is not possible to _generate_ media attachments. Right now, you could either use a specific image ID that is already available inside the Media Library or use a random image based on a set of available image IDs using [`randomElement()`](https://github.com/fzaninotto/Faker#fakerproviderbase).

Untested example that uses an attachment with the ID of `11`:

```
Trendwerk\Faker\Post:
  post{1..100}:
    post_title: '<sentence()>'
    meta:
      _thumbnail_id: 11
```

Hope this works for you.
